[package]
name = "onnx-proptest"
version = "0.19.13-pre"
edition = "2021"

[workspace]
members = []

[dependencies]
onnx-helpers = "2.2.1"
onnxruntime = { path = "../../../../github/onnxruntime-rs/onnxruntime" }
onnx-pb = "0.1.4"
anyhow = "1.0.56"
prost = "0.11.0"
tract-onnx = { path = "../../onnx" , version = "=0.19.13" }
proptest = "1.0.0"
