[package]
name = "tract"
version = "0.19.14"
authors = [ "Romain Liautaud <romain.liautaud@snips.ai>", "Mathieu Poumeyrol <kali@zoy.org>"]
license = "MIT/Apache-2.0"
description = "Tiny, no-nonsense, self contained, TensorFlow and ONNX inference"
repository = "https://github.com/snipsco/tract"
keywords = [ "TensorFlow", "NeuralNetworks" ]
categories = [ "science" ]
autobenches = false
edition = "2021"
include = [ "Cargo.toml", "src/**/*.rs", "LICENSE*" ]

[badges]
maintenance = { status = "actively-developed" }

[dependencies]
atty.workspace = true
box_drawing.workspace = true
clap.workspace = true
criterion.workspace = true
colorous.workspace = true
env_logger.workspace = true
flate2.workspace = true
lazy_static.workspace = true
log.workspace = true
ndarray-npy.workspace = true
nu-ansi-term.workspace = true
py_literal.workspace = true
readings-probe.workspace = true
regex.workspace = true
reqwest.workspace = true
rustls.workspace = true
scan_fmt.workspace = true
serde.workspace = true
serde_json.workspace = true
tract-core = { version = "=0.19.14", path = "../core" }
tract-hir = { version = "=0.19.14", path = "../hir" }
tract-nnef = { version = "=0.19.14", path = "../nnef" }
tract-libcli = { version = "=0.19.14", path = "../libcli" }
tract-pulse-opl = { optional = true, version = "=0.19.14", path = "../pulse-opl" }
tract-pulse = { optional = true, version = "=0.19.14", path = "../pulse" }
tract-kaldi = { optional = true, version = "=0.19.14", path = "../kaldi" }
tract-onnx = { optional = true, version = "=0.19.14", path = "../onnx" }
tract-tensorflow = { optional = true, version = "=0.19.14", path = "../tensorflow" }

[features]
default = ["kaldi", "onnx", "tf", "pulse", "pulse-opl"]
kaldi = [ "tract-kaldi", "tract-libcli/hir" ]
onnx = [ "tract-onnx", "tract-libcli/hir", "tract-libcli/onnx" ]
pulse-opl = [ "tract-pulse-opl" ]
pulse = [ "tract-pulse", "tract-pulse-opl" ]
tf = [ "tract-tensorflow", "tract-libcli/hir" ]
conform = [ "tract-tensorflow/conform"  ]
