[package]
name = "example-tensorflow-mobilenet-v2"
version = "0.19.6-pre"
authors = ["Mathieu Poumeyrol <kali@zoy.org>"]
license = "MIT/Apache-2.0"
edition = "2021"

[dependencies]
image.workspace = true
tract-tensorflow = { path = "../../tensorflow", version = "=0.19.6-pre" }
